spring.application.name=msusuario
server.port=8080

#EDNPOINTS
request.mapping.controller.usuariocontroller=/api/msusuario

#REDIS
spring.data.redis.host=localhost
spring.data.redis.port: 6379
spring.data.redis.time-to-live= 60000

logging.level.org.springframework.cache: TRACE
logging.level.org.springframework.data.redis: DEBUG
      
#BD
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/futbol
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false